/**/callback({
  "meta": {
    "Content-Type": "application/javascript; charset=utf-8",
    "X-RateLimit-Limit": "60",
    "X-RateLimit-Remaining": "56",
    "X-RateLimit-Reset": "1536643329",
    "Cache-Control": "public, max-age=60, s-maxage=60",
    "Vary": "Accept",
    "ETag": "\"5b400a83c891013a0384f7b402b5eb18\"",
    "Last-Modified": "Fri, 10 Aug 2018 03:27:35 GMT",
    "X-GitHub-Media-Type": "unknown, github.v3",
    "status": 200
  },
  "data": {
    "id": 2067351,
    "node_id": "MDEwOlJlcG9zaXRvcnkyMDY3MzUx",
    "name": "jquery-textext",
    "full_name": "alexgorbatchev/jquery-textext",
    "owner": {
      "login": "alexgorbatchev",
      "id": 65633,
      "node_id": "MDQ6VXNlcjY1NjMz",
      "avatar_url": "https://avatars0.githubusercontent.com/u/65633?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/alexgorbatchev",
      "html_url": "https://github.com/alexgorbatchev",
      "followers_url": "https://api.github.com/users/alexgorbatchev/followers",
      "following_url": "https://api.github.com/users/alexgorbatchev/following{/other_user}",
      "gists_url": "https://api.github.com/users/alexgorbatchev/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/alexgorbatchev/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/alexgorbatchev/subscriptions",
      "organizations_url": "https://api.github.com/users/alexgorbatchev/orgs",
      "repos_url": "https://api.github.com/users/alexgorbatchev/repos",
      "events_url": "https://api.github.com/users/alexgorbatchev/events{/privacy}",
      "received_events_url": "https://api.github.com/users/alexgorbatchev/received_events",
      "type": "User",
      "site_admin": false
    },
    "private": false,
    "html_url": "https://github.com/alexgorbatchev/jquery-textext",
    "description": "A super awesome, customizable text input supporting tags, autocomplete, ajax and other goodness in a crazy cool a-la cart way.",
    "fork": false,
    "url": "https://api.github.com/repos/alexgorbatchev/jquery-textext",
    "forks_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/forks",
    "keys_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/keys{/key_id}",
    "collaborators_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/collaborators{/collaborator}",
    "teams_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/teams",
    "hooks_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/hooks",
    "issue_events_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/issues/events{/number}",
    "events_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/events",
    "assignees_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/assignees{/user}",
    "branches_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/branches{/branch}",
    "tags_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/tags",
    "blobs_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/git/blobs{/sha}",
    "git_tags_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/git/tags{/sha}",
    "git_refs_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/git/refs{/sha}",
    "trees_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/git/trees{/sha}",
    "statuses_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/statuses/{sha}",
    "languages_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/languages",
    "stargazers_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/stargazers",
    "contributors_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/contributors",
    "subscribers_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/subscribers",
    "subscription_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/subscription",
    "commits_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/commits{/sha}",
    "git_commits_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/git/commits{/sha}",
    "comments_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/comments{/number}",
    "issue_comment_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/issues/comments{/number}",
    "contents_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/contents/{+path}",
    "compare_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/compare/{base}...{head}",
    "merges_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/merges",
    "archive_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/{archive_format}{/ref}",
    "downloads_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/downloads",
    "issues_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/issues{/number}",
    "pulls_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/pulls{/number}",
    "milestones_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/milestones{/number}",
    "notifications_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/notifications{?since,all,participating}",
    "labels_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/labels{/name}",
    "releases_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/releases{/id}",
    "deployments_url": "https://api.github.com/repos/alexgorbatchev/jquery-textext/deployments",
    "created_at": "2011-07-18T16:35:43Z",
    "updated_at": "2018-08-10T03:27:35Z",
    "pushed_at": "2018-08-31T16:06:46Z",
    "git_url": "git://github.com/alexgorbatchev/jquery-textext.git",
    "ssh_url": "git@github.com:alexgorbatchev/jquery-textext.git",
    "clone_url": "https://github.com/alexgorbatchev/jquery-textext.git",
    "svn_url": "https://github.com/alexgorbatchev/jquery-textext",
    "homepage": "http://textextjs.com",
    "size": 779,
    "stargazers_count": 1312,
    "watchers_count": 1312,
    "language": "JavaScript",
    "has_issues": true,
    "has_projects": true,
    "has_downloads": true,
    "has_wiki": false,
    "has_pages": false,
    "forks_count": 212,
    "mirror_url": null,
    "archived": false,
    "open_issues_count": 145,
    "license": {
      "key": "mit",
      "name": "MIT License",
      "spdx_id": "MIT",
      "url": "https://api.github.com/licenses/mit",
      "node_id": "MDc6TGljZW5zZTEz"
    },
    "forks": 212,
    "open_issues": 145,
    "watchers": 1312,
    "default_branch": "master",
    "network_count": 212,
    "subscribers_count": 50
  }
})
